---

#Copyright 2016 ShapeBlue
#
#Licensed under the Apache License, Version 2.0 (the "License");
#you may not use this file except in compliance with the License.
#You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
#Unless required by applicable law or agreed to in writing, software
#distributed under the License is distributed on an "AS IS" BASIS,
#WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#See the License for the specific language governing permissions and
#limitations under the License.

- name: Ensure NTP packages are installed
  apt: pkg=openntpd state=present update_cache=true

- name: Add specified repository into sources list.
  apt_repository: repo='deb "{{ baseurl_cloudstack }}" ./' state=present

- apt_key: url=https://packages.shapeblue.com/release.asc state=present

- name: Ensure CloudStack packages are installed
  apt: pkg=cloudstack-management state=present update_cache=true

- name: Ensure DB Client is present
  apt: pkg=mysql-client state=present

- name: install rng-tools to create entropy
  apt: pkg=rng-tools state=present

- name: Ensure vhd-util is present
  get_url: url="{{ vhdutil_url }}" dest=/usr/share/cloudstack-common/scripts/vm/hypervisor/xenserver/vhd-util mode=0755

- name: Ensure CloudStack Usage Service is installed
  apt: pkg=cloudstack-usage state=present update_cache=true

- include: ./setupdb.yml

- name: Ensure CloudStack Usage Service is started
  service: name=cloudstack-usage state=started

- name: copy cloudutil script to /usr/bin
  copy: src=cloudutil dest=/usr/bin/ mode=0755

- name: Ensure sshpass is installed
  apt: name=sshpass state=present update_cache=true

- name: Open 8096 when Marvin is required (Ubuntu)
  shell: "iptables -A INPUT -p tcp --dport ssh -j ACCEPT && iptables-save"
  when: num_marv_hosts > 0
